controllers:
    resource: ../src/Controller/
    type: attribute

api_token_refresh:
    path: /api/auth/refresh

api_login:
    path: /api/auth/login

api_platform:
    resource: .
    type: api_platform
    prefix: /api

_security_logout:
    resource: security.route_loader.logout
    type: service

api_auth_password_forgot:
    path: /api/auth/password/forgot
    controller: App\Controller\ResetPasswordController::request
    methods: [ POST ]

api_auth_password_reset:
    path: /api/auth/password/reset
    controller: App\Controller\ResetPasswordController::reset
    methods: [ POST ]

when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.php'
        prefix: /_error
