auth_controllers:
    resource: ../src/Controller/Auth/
    type: attribute

setup_controllers:
    resource: ../src/Controller/Setup/
    type: attribute

user_controllers:
    resource: ../src/Controller/User/
    type: attribute

api_token_refresh:
    path: /api/auth/refresh

api_login:
    path: /api/auth/login

api_platform:
    resource: .
    type: api_platform
    prefix: /api

_security_logout:
    resource: security.route_loader.logout
    type: service

when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.php'
        prefix: /_error
