gesdinet_jwt_refresh_token:
  refresh_token_class: App\Entity\RefreshToken
  ttl: '%env(int:JWT_REFRESH_TTL)%'
  single_use: true
  firewall: api
  token_parameter_name: '__Host-rt'
  cookie:
    enabled: true
    path: '/'
    domain: null
    same_site: strict
    http_only: true
    secure: true
    remove_token_from_body: true
