nelmio_cors:
  defaults:
    allow_origin: ['%env(ALLOWED_ORIGINS)%']
    allow_credentials: true
    allow_headers: ['Content-Type', 'Authorization', 'csrf-token']
    allow_methods: ['GET','POST','PUT','PATCH','DELETE','OPTIONS']
    max_age: 3600
  paths:
    '^/api/':
      allow_origin: ['%env(ALLOWED_ORIGINS)%']
